spring:
  application:
    name: spring-cloud-config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/IvanArantes/spring-cloud-config-server
          timeout: 4

server:
  port: 8888